import type { Metadata } from "next";
import GlobalContext from "@/app/context/globalContext";
import { Inter } from "next/font/google";
import Navbar from "./component/navbar";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContext>
          <Navbar />
          {children}
        </GlobalContext>
      </body>
    </html>
  );
}
